name: ai_exam_engine
description: "AI-powered examination platform"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  file_picker: ^10.3.8
  fl_chart: ^1.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.3
  google_fonts: ^6.3.3
  http: ^1.6.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  supabase_flutter: ^2.12.0
  syncfusion_flutter_pdf: ^32.1.21
  uuid: ^4.5.2
  flutter_secure_storage: ^10.0.0
  firebase_core: ^4.3.0
  animations: ^2.1.1
  flutter_animate: ^4.5.2
  onesignal_flutter: ^5.3.5
  excel: ^4.0.6
  xml: ^6.6.1
  timelines_plus: ^1.0.8
  firebase_ai: ^3.6.1
  firebase_app_check: ^0.4.1+3
  recase: ^4.1.0
  firebase_remote_config: ^6.1.4
  firebase_analytics: ^12.1.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/AI_Exam_Engine_Logo.svg
    - assets/logo/AI_Exam_Engine_Logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
